replicaCount: 2

image:
  repository: n8nio/n8n
  tag: nightly
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 443

n8n:
  encryptionKey: "4aONK7FNR0HNKZI1FH5znM12gz5iCxQA"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    acme.cert-manager.io/http01-ingress-class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
  hosts:
    - host: n8n.tarchunk.win
      paths:
        - path: /
          pathType: Prefix
  tls:  
    - secretName: n8n-tls
      hosts:
        - n8n.tarchunk.win
        

persistence:
  enabled: true
  storageClassName: "truenas-nfs-storage"   # ใส่ storage class ที่ cluster คุณมี เช่น "local-path" หรือ "longhorn"
  accessModes:
    - ReadWriteOnce
  size: 5Gi

resources: {}
