apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-runner-config
data:
  n8n-task-runners.json: |
    {
      "task-runners": [
        {
          "runner-type": "javascript",
          "workdir": "/home/runner",
          "health-check-server-port": "5580",
          "allowed-env": [
            "N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT",
            "N8N_RUNNERS_TASK_TIMEOUT"
          ],
          "env-overrides": {
            "NODE_FUNCTION_ALLOW_EXTERNAL": "ccxt"
          }
        },
        {
          "runner-type": "python",
          "PYTHONPATH": "/opt/runners/task-runner-python",
          "workdir": "/home/runner",
          "health-check-server-port": "5681",
          "allowed-env": [
            "N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT",
            "N8N_RUNNERS_TASK_TIMEOUT"
          ],
          "env-overrides": {
            "PYTHONPATH": "/opt/runners/task-runner-python",
            "N8N_RUNNERS_STDLIB_ALLOW": "json,sys",             
            "N8N_RUNNERS_EXTERNAL_ALLOW": "talib,ta-lib,pillow"     
          }
        }
      ]
    }
