apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-runner-config
data:
  n8n-task-runners.json: |
    {
      "task-runners": [
        {
          "runner-type": "javascript",
          "workdir": "/home/runner",
          "command": "/usr/local/bin/node",
          "args": [
            "--disallow-code-generation-from-strings",
            "--disable-proto=delete",
            "/opt/runners/task-runner-javascript/dist/start.js"
          ],
          "health-check-server-port": "5580",
          "allowed-env": [
            "N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT",
            "N8N_RUNNERS_TASK_TIMEOUT"
          ],
          "env-overrides": {
            "NODE_FUNCTION_ALLOW_EXTERNAL": "ccxt"
          }
        },
        {
          "runner-type": "python",
          "PYTHONPATH": "/opt/runners/task-runner-python",
          "workdir": "/home/runner",
          "command": "/opt/runners/task-runner-python/.venv/bin/python",
          "health-check-server-port": "5681",
          "allowed-env": [
            "N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT",
            "N8N_RUNNERS_TASK_TIMEOUT"
          ],
          "env-overrides": {
            "PYTHONPATH": "/opt/runners/task-runner-python",
            "N8N_RUNNERS_STDLIB_ALLOW": "json,sys",             
            "N8N_RUNNERS_EXTERNAL_ALLOW": "numpy,pandas,talib,ta-lib"     
          }
        }
      ]
    }
