apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
spec:
  topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: n8n
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "n8n.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "n8n.name" . }}
    spec:
      containers:
        - name: n8n
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["start"]
          ports:
            - containerPort: 5678
          env:
            - name: N8N_PORT
              value: "5678"
            - name: N8N_HOST
              # value: "0.0.0.0"
              value: "{{ (index .Values.ingress.hosts 0).host }}"
            - name: WEBHOOK_URL
              value: "https://{{ (index .Values.ingress.hosts 0).host }}/"
            - name: N8N_ENCRYPTION_KEY
              value: "{{ .Values.n8n.encryptionKey }}"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "false"
            - name: DB_TYPE
              value: "postgresdb"
            - name: N8N_PROTOCOL
              value: "https"
            - name: DB_POSTGRESDB_HOST
              value: "192.168.1.44"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: "n8n_db"
            - name: DB_POSTGRESDB_USER
              value: "n8n"
            - name: DB_POSTGRESDB_PASSWORD
              value: "4aONK7FNR0HNKZI1FH5znM12gz5iCxQA"
            - name:  N8N_PAYLOAD_SIZE_MAX
              value: "100"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_RUNNERS_MODE
              value: "external"
            - name: N8N_RUNNERS_AUTH_TOKEN
              value: "my-super-secret-token"
            - name: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
              value: "0.0.0.0"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000 
        - name: n8n-runner
          image: "registry.registry.svc.cluster.local:5000/n8n-runner:46"
          # command: ["sleep", "3600"]    
          imagePullPolicy: IfNotPresent
          env:
            - name: N8N_RUNNERS_AUTH_TOKEN
              value: "my-super-secret-token"
            - name: N8N_RUNNERS_TASK_BROKER_URI
              value: "http://127.0.0.1:5679"
            - name: N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT
              value: "15"
            - name: N8N_RUNNERS_TASK_TIMEOUT
              value: "300"
          volumeMounts:
            - name: runner-config
              mountPath: /etc/n8n-task-runners.json
              subPath: n8n-task-runners.json
          securityContext:
            runAsUser: 0
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "n8n.fullname" . }}{{ end }}
        - name: runner-config
          configMap:
            name: n8n-runner-config